wip: changes [dry]

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,5 +1,3 @@
-name: OpenAPI Specification CI
-
 on:
   push:
   pull_request:
@@ -31,29 +29,29 @@ jobs:
 
       - run: pnpm install
 
-      - name: pnpm run lint-ci
+      - if: github.event_name == 'push'
         run: |
-          output=$(pnpm run lint-ci 2>&1)
-          exit_code=$?
+          changes=$(git diff --name-only --diff-filter=d "${{ github.event.commits[0].id }}~1" "${{ github.event.commits[0].id }}")
+          echo "changes=$changes" >> $GITHUB_ENV
 
-          if [ "${{ github.event_name }}" = "push" ]; then
-            changes=$(git diff --name-only --diff-filter=d "${{ github.event.commits[0].id }}~1" "${{ github.event.commits[0].id }}")
-          elif [ "${{ github.event_name }}" = "pull_request" ]; then
-            changes=$(git diff --name-only --diff-filter=d "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}")
-          fi
+      - if: github.event_name == 'pull_request'
+        run: |
+          changes=$(git diff --name-only --diff-filter=d "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}")
+          echo "changes=$changes" >> $GITHUB_ENV
 
-          if [ -n "$changes" ]; then
-            filtered_output=$(echo "$output" | grep -E "($(echo "$changes" | tr '\n' '|' | sed 's/|$//'))" || true)
+      - 
+        # Files were changed, lint & filter results to only changed files.
+        if: env.changes != ''
+        run: |
+          pattern=$(echo "$changes" | tr '\n' '|' | sed 's/|$//')
 
-            if [ -n "$filtered_output" ]; then
-              echo "$filtered_output"
-              echo "$output"
-
-              exit ${exit_code:-1}
-            fi
-          fi
-
-          echo "$output"
+          pnpm run lint-ci 2>&1 | grep -E "$pattern" || true
+          exit ${PIPESTATUS[0]:-1}
+      - 
+        # Files were not changed, lint but don't fail.
+        if: env.changes == ''
+        continue-on-error: true
+        run: pnpm run lint-ci
 
   bundle:
     runs-on: ubuntu-latest
@@ -93,7 +91,7 @@ jobs:
   release:
     runs-on: ubuntu-latest
     needs: bundle
-    if: github.ref == 'refs/heads/main'
+    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[dry]')
     outputs:
       release: ${{ steps.data.outputs.release }}
     steps:
@@ -200,66 +198,3 @@ jobs:
           GH_TOKEN: ${{ secrets.RELEASE_DISPATCH_TOKEN }}
           repository: ${{ matrix.repository }}
           release: ${{ needs.release.outputs.release }}
-
-#  pages:
-#    name: Upload OpenAPI specification to GitHub Pages
-#    runs-on: ubuntu-latest
-#    needs: bundle
-#    # Only if main branch
-#    if: github.ref == 'refs/heads/main'
-#    steps:
-#      - uses: actions/checkout@v4
-#
-#      - uses: actions/download-artifact@v4
-#        with:
-#          name: openapi.yaml
-#          path: dist
-#
-#      - name: Disable Jekyll for Github Pages
-#        run: sudo touch dist/.nojekyll; sudo touch dist/index.html
-#
-#      - name: Deploy Bundle to Github Pages 🚀
-#        uses: JamesIves/github-pages-deploy-action@v4
-#        with:
-#          branch: gh-pages
-#          folder: dist
-#
-#  version_check:
-#    name: Check if OpenAPI specification version is matching tag
-#    runs-on: ubuntu-latest
-#    needs: bundle
-#    # Only if tag "release/*" is pushed
-#    if: ${{ startsWith(github.ref, 'refs/tags/release/') }}
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: Check if OpenAPI specification version is matching tag
-#        # Tag will be e.g., "release/1.0.0", check if this matches the version in openapi/openapi.yaml
-#        run: |
-#          if [[ $(cat openapi/openapi.yaml | grep -oP '(?<=version: ).*') != $(echo $GITHUB_REF | grep -oP '(?<=release/).*') ]]; then
-#            echo "OpenAPI specification version does not match tag!"
-#            exit 1
-#          fi
-#
-#  # https://blog.marcnuri.com/triggering-github-actions-across-different-repositories
-#  # Make sure this is same as in sdk_generate.yaml
-#  sdk_generate:
-#    runs-on: ubuntu-latest
-#    needs: version_check
-#    name: Trigger Remote SDK builds
-#    strategy:
-#      matrix:
-#        project:
-#          - javascript
-#          - csharp
-#          - python
-#          - java
-#          - rust
-#          - dart
-#    steps:
-#      - name: Triggering build SDK - ${{ matrix.node }}
-#        run: |
-#          curl -X POST https://api.github.com/repos/vrchatapi/vrchatapi-${{ matrix.project }}/dispatches \
-#          -H 'Accept: application/vnd.github.everest-preview+json' \
-#          -u ${{ secrets.ACCESS_TOKEN }} \
-#          --data '{"event_type": "spec_release"}'
-#
